spring.application.name=crud-posts 

# إعدادات قاعدة البيانات PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/crud_spring_boot
spring.datasource.username=postgres
spring.datasource.password=root

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# إعدادات JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# منفذ التطبيق
server.port=8080